#!/usr/bin/env bash
set -e

cd "${0%/*}"/..

for file in "$PWD"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  [[ "readme script vscode" =~ $name ]] && continue
  [ -e "${HOME}/${dotname}" ] && continue
  git --git-dir "${file}/.git" rev-parse --git-dir &>/dev/null && continue

  ln -sfnv ${file#$HOME/} "${HOME}/${dotname}"
done

# VSCODE_USER_DIR=~/Library/Application\ Support/Code/User
# mkdir -p "$VSCODE_USER_DIR"
# for file in "$PWD/vscode/"*; do
#   name="$(basename "$file")"
#   [ -e "$VSCODE_USER_DIR/$name" ] || ln -sfnv "$file" "$VSCODE_USER_DIR/$name"
# done

# install vim necessities
vim_plug_folder=~/.vim/autoload/plug.vim
[ ! -e $vim_plug_folder ] && curl -fLo $vim_plug_folder --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim_folder=~/.vim
mkdir -pv "$vim_folder/undo"
mkdir -pv "$vim_folder/backup"
