#!/bin/bash
set -e

if ! [ -e ~/.vim ]; then
  vim_plug_folder=~/.vim/autoload/plug.vim
  [ ! -e $vim_plug_folder ] && curl -fLo $vim_plug_folder --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim_folder=~/.vim
  mkdir -pv "$vim_folder/undo"
  mkdir -pv "$vim_folder/backup"
fi

# install tmux
sudo apt update

sudo apt install -y git

sudo apt install -y automake
sudo apt install -y bison
sudo apt install -y build-essential
sudo apt install -y pkg-config
sudo apt install -y libevent-dev
sudo apt install -y libncurses5-dev

rm -fr /tmp/tmux
git clone https://github.com/tmux/tmux.git /tmp/tmux
cd /tmp/tmux
git checkout master
sh autogen.sh
./configure && make
sudo make install
cd -
rm -fr /tmp/tmux

# if ! [ -e ~/.rbenv ]; then
#   git clone https://github.com/rbenv/rbenv ~/.rbenv
#   mkdir -p ~/.rbenv/{cache,plugins}
# 
#   ~/.rbenv/src/configure
#   make -C ~/.rbenv/src
# 
#   if ! [ -e ~/p/ruby-build ]; then
#     mkdir -p ~/p
#     git clone https://github.com/rbenv/ruby-build ~/p/ruby-build
#   fi
# 
#   ln -s ~/p/ruby-build ~/.rbenv/plugins/ruby-build
#   ruby_version="$(~/.rbenv/bin/rbenv install --list | awk '{print $1}' | grep '^2\.7\.' | tail -1)"
#   RUBY_CONFIGURE_OPTS=--disable-install-docs ~/.rbenv/bin/rbenv install "$ruby_version"
#   ~/.rbenv/bin/rbenv global "$ruby_version"
# fi
